---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Set mydistribution
      ansible.builtin.set_fact:
#        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"
        mydistribution: "centos"

#    - name: Add signing key
#      ansible.builtin.rpm_key:
#        key: "http://iranetrepo-1:8081/repository/docker-yum-repo/gpg"
#        state: present

    - name: Add repository into repo.d list
      ansible.builtin.yum_repository:
        name: docker
        description: Docker repository
        baseurl: "http://iranetrepo-1:8081/repository/docker-yum-install/$releasever/$basearch/stable"
        enabled: true
        gpgcheck: false
        gpgkey: "http://iranetrepo-1:8081/repository/docker-yum-repo/gpg"

    - name: Install Docker
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: true

    - name: Start Docker
      ansible.builtin.service:
        name: "docker"
        enabled: true
        state: started