---
- name: k8s helm
  hosts: kuber_local
  vars:
    chart_name: "nginx-server"
    myproject: "ansible-examples"
  tasks:
    - name: helm chart absent
      kubernetes.core.helm:
        name: "{{ chart_name }}"
        namespace: "{{ myproject }}"
        release_state: absent
